networks:
  knight_challenge:
    driver: bridge  
      
services:

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      ME_CONFIG_MONGODB_ADMINUSERNAME: root 
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - '27017:27017'
    volumes:
      - /db
  #networks:
  #  - knight_challenge      

  mongo_express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/knightdb
      ME_CONFIG_BASICAUTH: false
    links:
      - mongodb
    #networks:
    #  - knight_challenge

  #nodejs:
  #  container_name: nodejs_knight
  #  build: .
  #  command: "npm run start"
    #volumes:
    #  - ./:/node-app
    #  - ./node_modules:/node-app/node_modules
  #  environment:
  #    NODE_ENV: development
  #  expose:
  #    - 3000
  #  ports:
  #    - 3000:3000
  #  depends_on:
  #    - mongodb




#networks:
#    knight_challenge:
#      driver: bridge  
      
#services:
  
#  mongo:
#    image: mongo
#    restart: always
#    volumes:
#      - /db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
    #networks:
    #  - knight_challenge      

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 30010:3090
#    environment:
#      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_BASICAUTH: false
    #depends_on:
    #  - mongo
    #links:
    #  - mongo
    #networks:
    #  - knight_challenge


  #mongo-express:
    #image: mongo-express
    #restart: always 
    #restart: unless-stopped
    #ports:
    #  - 3000:3000
    #environment:
      #ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      #ME_CONFIG_BASICAUTH_USERNAME: aevangelista
      #ME_CONFIG_BASICAUTH_PASSWORD: knight2024
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: knight2024
      #ME_CONFIG_MONGODB_PORT: 8000
      #ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    #links:
    #  - mongo
    #networks:
    #  - mongo-compose-network

  #mongo:
    #image: mongo
    #restart: always
    #restart: unless-stopped 
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: knight2024
    #ports:
    #  - "27017:27017"
    #volumes:
    #  - /db
    #networks:
    #  - mongo-compose-network

#networks: 
#    mongo-compose-network:
 #     driver: bridge

